### ISSUE TITLE
Why is the db file in VC

### ISSUE THREAD

**Issue by circlesabound** [unswpcsoc/PCSocBot#12]
Security 101
@davids3 you're doxxing yourself

**Comment by davids3** [comment]
Thanks for the heads up, I've fixed it... really emphasizes the importance of a .gitignore file

**Comment by cry** [comment]
@davids3 commit history shows your secrets still https://github.com/unswpcsoc/PCSocBot/commit/2726489613fca56dfd99750cbdc7c0a890198cbc. Rebase the commit out to remove it completely.
