### ISSUE TITLE
Invalid users in tag pings

### ISSUE THREAD

**Issue by davids3** [unswpcsoc/PCSocBot#77]
Invalid users display in the ask pings, need to add check to see if they are still in the server before displaying.

Also need to fix `modremove` so we can remove users who have left the server, and optionally make it so they don't display on platform and user lists either.

![Screenshot_20190513-081620](https://user-images.githubusercontent.com/8898854/57588433-6b0b0680-7557-11e9-9fb9-25261cb581e9.jpg)

**Comment by VineBalloon** [comment]
Working on it now.

**Comment by VineBalloon** [comment]
Closing due to migration to Go, which already has features to check valid users in the db.
